[package]
name = "herkos"
version = "0.1.0"
edition = "2024"
description = "Compile-Time Memory Isolation via WebAssembly and Rust Transpilation"
license = "Apache-2.0"
repository = "https://github.com/arnaudriess/herkos"

[dependencies]
