[project]
name = "herkos-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "myst-parser==5.0.0",
    "sphinx==8.3.0",
    "sphinx-needs==6.3.0",
]
